language: go
go:
  - 1.9

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

before_install:
- go get -u github.com/kyoh86/richgo
- go get github.com/axw/gocov/gocov
- go get -u github.com/golang/lint/golint

script:
  - go vet ./...
  - go test ./...
  - golint -set_exit_status .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      git config credential.helper "store --file=.git/credentials";
      echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials;
      go install;
      go-tag;
    fi
